name: zheeta
description: Zheeta... The Social Affiliate Networking Platform
publish_to: "none"

version: 1.1.6+2 # iOS version number
# version: 1.1.5+7 # Android version number

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  animations: ^2.0.11
  carousel_slider: ^5.1.1
  appinio_swiper: ^2.1.1
  dotted_border: ^3.0.1
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0

  # Forms
  intl_phone_field: ^3.2.0
  otp: ^3.1.4
  pin_code_fields: ^8.0.1

  # Media
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Networking
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  jwt_decode: ^0.3.1

  # Caching
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

  # Location
  geocoding: ^4.0.0
  geolocator: ^14.0.1

  # Routing
  auto_route: ^10.1.0+1

  # Purchases
  in_app_purchase: ^3.2.3

  # Utilities
  intl: ^0.20.2
  age_calculator: ^1.0.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  share_plus: ^11.0.0
  firebase_messaging: ^15.2.7
  firebase_core: ^3.14.0
  flutter_local_notifications: ^18.0.1
  app_links: ^6.4.0
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  timeago: ^3.7.1
  mime: ^2.0.0
  app_settings: ^6.1.1
  flutter_dotenv: ^5.2.1
  device_preview: ^1.1.0


  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.5.3
  json_serializable: ^6.9.5
  injectable_generator: ^2.7.0
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  auto_route_generator: ^10.2.3
#  mockito: ^5.4.5
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/json/
    - assets/images/
    - assets/images/icons/
    - assets/images/heroo.png

  fonts:
    - family: MuseoModerno
      fonts:
        - asset: assets/fonts/MuseoModerno-Black.ttf
        - asset: assets/fonts/MuseoModerno-Bold.ttf
        - asset: assets/fonts/MuseoModerno-ExtraBold.ttf
        - asset: assets/fonts/MuseoModerno-ExtraLight.ttf
        - asset: assets/fonts/MuseoModerno-Light.ttf
        - asset: assets/fonts/MuseoModerno-Medium.ttf
        - asset: assets/fonts/MuseoModerno-Regular.ttf
        - asset: assets/fonts/MuseoModerno-SemiBold.ttf
        - asset: assets/fonts/MuseoModerno-Thin.ttf

    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/static/Outfit-Black.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit/static/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit/static/Outfit-ExtraLight.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Light.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit/static/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Thin.ttf
